// =============================================================================
// NZA-PV — locked Phase 1 schema (v1.0)
//
// LOCKED at end of Phase 1. Any change in Phase 2+ MUST go via a migration
// (bump SCHEMA_VERSION, add a `migrate_v1_to_v2` function), never an in-place
// edit of these types.
// =============================================================================

import type { Polygon } from 'geojson';

export type { Polygon } from 'geojson';

export const SCHEMA_VERSION = '1.0' as const;
export type SchemaVersion = typeof SCHEMA_VERSION;

// --- Project file -----------------------------------------------------------

export type ProjectFile = {
  schema_version: SchemaVersion;
  project: ProjectMeta;
  site?: Site;
  buildings: Building[];
  /** Optional camera state, persisted so `Load` restores the same viewport. */
  view?: CameraState;
};

export type ProjectMeta = {
  id: string;
  name: string;
  created_at: string; // ISO 8601
  last_modified: string; // ISO 8601
  notes?: string;
};

export type Site = {
  perimeter?: Polygon;
  centroid?: [number, number];
  country?: string;
};

export type CameraState = {
  /** Map (2D) viewport state. */
  map?: { center: [number, number]; zoom: number; bearing: number; pitch: number };
  /** 3D scene state. */
  scene?: { target: [number, number, number]; position: [number, number, number] };
};

// --- Building ---------------------------------------------------------------

export type Building = {
  id: string;
  name: string;
  footprint: Polygon;
  storeys: number;
  storey_height_m: number; // default 3
  eave_height_m: number; // = storeys × storey_height_m, overridable
  roof: Roof;
  /** Generated by the calc engine; cached for performance. */
  faces: RoofFace[];
};

// --- Roofs ------------------------------------------------------------------

export type RidgeAxisChoice = 'longest' | 'shortest' | 'custom';

export type RoofFlat = { style: 'flat'; parapet_height_m: number };

export type RoofMono = {
  style: 'mono';
  pitch_deg: number;
  /** Cardinal direction of the high edge, or degrees from north. */
  high_side: 'N' | 'E' | 'S' | 'W' | number;
};

/** World bearing of the ridge in degrees from north (0 = N, 90 = E). When
 *  set, the roof's ridge stays in this world direction even as the building
 *  is rotated — mirroring how `RoofMono.high_side` anchors the slope to a
 *  world cardinal. The generator snaps to whichever OBB axis is closer to
 *  this bearing each time it regenerates. When undefined, the roof falls
 *  back to its OBB-relative `ridge_axis` / `orientation` enum (the old
 *  behavior, used by saved files written before this field existed). */
export type RidgeBearingDeg = number;

export type RoofGable = {
  style: 'gable';
  pitch_deg: number;
  ridge_axis: RidgeAxisChoice;
  ridge_rotation_deg?: number;
  ridge_bearing_deg?: RidgeBearingDeg;
};

export type RoofHip = {
  style: 'hip';
  pitch_deg: number;
  /** 'longest' (default) — ridge runs along the long axis; 'shortest' — ridge
   *  swaps to the short axis (a 90° rotation of the whole roof shape). */
  orientation?: 'longest' | 'shortest';
  ridge_bearing_deg?: RidgeBearingDeg;
};

export type RoofDutchHip = {
  style: 'dutch_hip';
  pitch_deg: number;
  ridge_axis: RidgeAxisChoice;
  ridge_rotation_deg?: number;
  ridge_bearing_deg?: RidgeBearingDeg;
  hip_ratio: number; // 0..1 — fraction of half-span occupied by the hip
};

export type RoofGambrel = {
  style: 'gambrel';
  lower_pitch_deg: number;
  upper_pitch_deg: number;
  break_height_m: number;
  ridge_axis: RidgeAxisChoice;
  ridge_rotation_deg?: number;
  ridge_bearing_deg?: RidgeBearingDeg;
};

export type RoofMansard = {
  style: 'mansard';
  lower_pitch_deg: number;
  upper_pitch_deg: number;
  break_height_m: number;
  ridge_axis: RidgeAxisChoice;
  ridge_rotation_deg?: number;
  ridge_bearing_deg?: RidgeBearingDeg;
};

export type RoofSaltbox = {
  style: 'saltbox';
  front_pitch_deg: number;
  back_pitch_deg: number;
  ridge_offset_pct: number; // -50..+50; 0 = centred
  ridge_axis: RidgeAxisChoice;
  ridge_rotation_deg?: number;
  ridge_bearing_deg?: RidgeBearingDeg;
};

export type RoofSawtooth = {
  style: 'sawtooth';
  pitch_count: number;
  pitch_deg: number;
  glazing_strip_width_m: number;
  /** 'longest' (default) — pitches run across the building's long axis;
   *  'shortest' — pitches run across the short axis (rotated 90°). */
  orientation?: 'longest' | 'shortest';
  ridge_bearing_deg?: RidgeBearingDeg;
};

export type RoofButterfly = {
  style: 'butterfly';
  pitch_deg: number;
  valley_depth_m: number;
  /** 'longest' (default) — valley runs along the building's long axis;
   *  'shortest' — valley runs along the short axis (rotated 90°). */
  orientation?: 'longest' | 'shortest';
  ridge_bearing_deg?: RidgeBearingDeg;
};

export type RoofPyramid = { style: 'pyramid'; pitch_deg: number };

export type RoofCrossGabled = { style: 'cross_gabled'; pitch_deg: number };

/** Parallel gables (also known as ridge-and-furrow or M-roof) — `pitch_count`
 *  full A-frame gable bays repeated across the long axis, all ridges
 *  parallel. Like sawtooth, but each bay is a symmetric triangle instead
 *  of a slope + glazing strip. */
export type RoofParallelGables = {
  style: 'parallel_gables';
  pitch_count: number;
  pitch_deg: number;
  orientation?: 'longest' | 'shortest';
  ridge_bearing_deg?: RidgeBearingDeg;
};

export type Roof =
  | RoofFlat
  | RoofMono
  | RoofGable
  | RoofHip
  | RoofDutchHip
  | RoofGambrel
  | RoofMansard
  | RoofSaltbox
  | RoofSawtooth
  | RoofButterfly
  | RoofPyramid
  | RoofCrossGabled
  | RoofParallelGables;

export type RoofStyle = Roof['style'];

export const ROOF_STYLES: readonly RoofStyle[] = [
  'flat',
  'mono',
  'gable',
  'hip',
  'dutch_hip',
  'gambrel',
  'mansard',
  'saltbox',
  'sawtooth',
  'parallel_gables',
  'butterfly',
  'pyramid',
  'cross_gabled',
] as const;

// --- Roof faces -------------------------------------------------------------

export type FaceRole =
  | 'main'
  | 'hip_end'
  | 'gable_end_wall'
  | 'dormer'
  | 'sawtooth_pitch'
  | 'sawtooth_glazing'
  | 'mansard_lower'
  | 'mansard_upper'
  | 'gambrel_lower'
  | 'gambrel_upper';

export type Cardinal = 'N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW' | 'flat';

export type RoofFace = {
  id: string;
  role: FaceRole;
  cardinal: Cardinal;
  /** 3D polygon — vertices carry z (height in metres above ground). */
  geometry: Polygon;
  area_m2: number;
  tilt_deg: number;
  azimuth_deg: number;
  is_pv_eligible: boolean; // default: 0 ≤ tilt ≤ 60° → true
  max_coverage_pct: number; // default 70
  panel_size_m2: number; // default 1.95
};

// --- Defaults ---------------------------------------------------------------

export const DEFAULT_STOREY_HEIGHT_M = 3;
export const DEFAULT_PANEL_SIZE_M2 = 1.95;
export const DEFAULT_MAX_COVERAGE_PCT = 70;
export const PV_ELIGIBLE_TILT_MIN_DEG = 0;
export const PV_ELIGIBLE_TILT_MAX_DEG = 60;

export const PANEL_PRESETS: readonly { label: string; m2: number }[] = [
  { label: 'Standard (1.95 m²)', m2: 1.95 },
  { label: 'Commercial (2.0 m²)', m2: 2.0 },
  { label: 'Half-cut (1.75 m²)', m2: 1.75 },
] as const;

// --- Type guards ------------------------------------------------------------

export function isProjectFile(value: unknown): value is ProjectFile {
  if (!value || typeof value !== 'object') return false;
  const v = value as Partial<ProjectFile>;
  return (
    v.schema_version === SCHEMA_VERSION &&
    typeof v.project === 'object' &&
    Array.isArray(v.buildings)
  );
}
